from collections import Counter, defaultdict
from itertools import combinations
import time

##  "Don't optimise until you've measured" - David Patterson, Computer Organisation

##  TODO: break string check out into separate function, minimise calls to Counter()

class Solution:

    def longestBalanced(self, s: str) -> int:

        start = time.time()

        ##  If a list is not found inside the dict's value, it is autogenerated.

        ss_data = defaultdict(list)

        ##  Don't actually need a key-value store, but do want O(1) lookups.

        ss_uniqs = {}

        all_subs = []

        ##  Generate all substrings in useful order (as opposed to s[i:j]).
        ##  As in, largest string to smallest string.

        for q in range(2, len(s) + 2):

            for i in range(0, len(s)):

                sub_s = s[i:i + q]

                ##  Simplest sliding window implementation involves a break.

                if len(sub_s) < q:
                    break

                ##  Discard all strings of odd length.

                if len(sub_s) % 2 == 0:

                    all_subs += [(sub_s, i, len(sub_s))]

        ##print("all_subs:\n", all_subs)

        ##  Count quantities within each substring, store as lookup.
        ##  Store metadata regarding instances of each substring.

        part_1 = time.time()
        print(part_1 - start)

        for (sub_s, pos, sub_s_len) in all_subs:

            if sub_s != '':
                ss_data[sub_s] += [(pos, sub_s_len)]

                if sub_s not in ss_uniqs:
                    ss_uniqs[sub_s] = 0

        part_2 = time.time()
        print("part 2", part_2 - start)

        ##print(ss_data)
        ##print(ss_counts)
            
        ##  For all substrings, check if they are a perfect match, or if a swap is available.

        #print(len(ss_counts.keys()))

        for sub_s in list(ss_uniqs.keys())[::-1]:

            ##  Counter is computationally heavy, so perform on-the-fly (i.e. minimally).
            ##  This is the bottleneck in the whole script.

            counts = Counter(sub_s)

            ##print("sub_s:", sub_s)

            target = None

            ##print(cand)

            ##  If equal quantities of 1 and 0, substring is best.

            if counts['0'] == counts['1']:
                return len(sub_s)

            ##  If there is only 1 character difference: viable candidate.

            elif counts['0'] - 1 == counts['1'] + 1:

                target = '1'

            elif counts['0'] + 1 == counts['1'] - 1:

                target = '0'

            ##  Compare with rest of string, seeking a 1 or a 0.

            if target is not None:

                for (pos, sub_s_len) in ss_data[sub_s]:

                    pre_str = s[0:pos]

                    post_str = s[(pos + sub_s_len):]

                    ##print(pre_str, sub_s, post_str)

                    if target in pre_str or target in post_str:

                        part_3 = time.time()
                        print("part 3", part_3 - start)

                        return sub_s_len

        return 0
        
